#!/usr/bin/env python3
"""Generate conservative per-level texture preload manifests for sm64ex-alo."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import zipfile
from datetime import datetime, timezone
from pathlib import Path


COMPILED_TABLE_COMMENT = "/* Auto-generated by tools/generate_wiiu_preload_manifests.py. Do not edit. */"
REPO_GLOBAL_TEXTURES = (
    "gfx/textures/segment2/custom/shadow_spike_custom.ia8.png",
)
DEFAULT_OVERRIDES_PATH = Path("tools/wiiu_preload_overrides.json")


LEVEL_RE = re.compile(
    r'^DEFINE_LEVEL\("(?P<rom>[^"]*)",\s*(?P<enum>[^,]+),\s*(?P<course>[^,]+),'
    r'\s*(?P<folder>[^,]+),\s*(?P<texture>[^,]+),'
)
DIRS_RE = re.compile(r"^(?P<name>[A-Z0-9_]+_DIRS)\s*:=\s*(?P<value>.*)$", re.MULTILINE)
TEXTURE_DIR_RE = re.compile(
    r"^(?P<textures>[A-Z0-9_]+_TEXTURES)\s*:=.*\$\((?P<dirs>[A-Z0-9_]+_DIRS)\)", re.MULTILINE
)
GROUP_RE = re.compile(
    r"actors/(?P<group>group\d+|common\d+)\.o:.*\$\((?P<textures>[A-Z0-9_]+_TEXTURES)", re.MULTILINE
)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_png_size(path: Path) -> tuple[int, int]:
    with path.open("rb") as stream:
        header = stream.read(24)
    if len(header) != 24 or header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        raise ValueError(f"Invalid PNG header: {path}")
    return struct.unpack(">II", header[16:24])


def read_png_size_from_zip(archive: zipfile.ZipFile, name: str) -> tuple[int, int]:
    with archive.open(name) as stream:
        header = stream.read(24)
    if len(header) != 24 or header[:8] != b"\x89PNG\r\n\x1a\n" or header[12:16] != b"IHDR":
        raise ValueError(f"Invalid PNG header in base archive: {name}")
    return struct.unpack(">II", header[16:24])


def load_texture_zip_entries(path: Path) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    with zipfile.ZipFile(path) as archive:
        for info in archive.infolist():
            name = info.filename.replace("\\", "/")
            if not name.startswith("gfx/") or not name.endswith(".png"):
                continue
            width, height = read_png_size_from_zip(archive, info.filename)
            parts = name.split("/", 2)
            entries.append({
                "path": name,
                "family": parts[1] if len(parts) > 1 else "gfx",
                "output_size": [width, height],
                "output_png_bytes": info.file_size,
                "estimated_rgba8_bytes": width * height * 4,
            })
    return entries


def parse_yaml_value(value: str):
    value = value.strip()
    if value == "null":
        return None
    if value in ("true", "false"):
        return value == "true"
    if value.startswith("[") and value.endswith("]"):
        body = value[1:-1].strip()
        if not body:
            return []
        return [item.strip().strip('"\'') for item in body.split(",")]
    return value.strip('"\'')


def parse_level_yaml(path: Path) -> dict[str, object]:
    result: dict[str, object] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = parse_yaml_value(value)
    return result


def parse_levels(path: Path) -> dict[str, dict[str, object]]:
    levels: dict[str, dict[str, object]] = {}
    level_id = 1
    row_re = re.compile(r"^(DEFINE_LEVEL|STUB_LEVEL)\((.*)\)")
    for line in path.read_text(encoding="utf-8").splitlines():
        row = row_re.match(line)
        if not row:
            continue
        if row.group(1) == "STUB_LEVEL":
            level_id += 1
            continue
        match = LEVEL_RE.match(line)
        if not match:
            raise ValueError(f"Unable to parse level definition: {line}")
        folder = match.group("folder").strip()
        levels[folder] = {
            "id": level_id,
            "enum": match.group("enum").strip(),
            "course": match.group("course").strip(),
            "rom_name": match.group("rom"),
            "texture_bin_from_level_defines": match.group("texture").strip(),
        }
        level_id += 1
    return levels


def parse_actor_groups(path: Path) -> dict[str, list[str]]:
    text = path.read_text(encoding="utf-8")
    directory_variables = {
        match.group("name"): match.group("value").split()
        for match in DIRS_RE.finditer(text)
    }
    textures_to_directories = {
        match.group("textures"): match.group("dirs")
        for match in TEXTURE_DIR_RE.finditer(text)
    }
    groups: dict[str, list[str]] = {}
    for match in GROUP_RE.finditer(text):
        directory_variable = textures_to_directories.get(match.group("textures"))
        if directory_variable:
            groups[match.group("group")] = directory_variables[directory_variable]
    return groups


def parse_level_script(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    texture_match = re.search(
        r"LOAD_MIO0_TEXTURE\s*\([^\n]*?_([A-Za-z0-9_]+)_mio0SegmentRomStart", text
    )
    skybox_match = re.search(
        r"LOAD_MIO0\s*\([^\n]*?_([A-Za-z0-9_]+)_skybox_mio0SegmentRomStart", text
    )
    groups = sorted(set(re.findall(
        r"LOAD_MIO0\s*\([^\n]*_(group\d+|common\d+)_mio0SegmentRomStart", text
    )))
    return {
        "texture_bin": texture_match.group(1) if texture_match else None,
        "skybox_bin": skybox_match.group(1) if skybox_match else None,
        "actor_bins": [group for group in groups if group.startswith("group")],
        "common_bins": [group for group in groups if group.startswith("common")],
        "effects": bool(re.search(r"_effect_mio0SegmentRomStart", text)),
    }


def prefix_matches(paths: set[str], prefix: str) -> set[str]:
    return {path for path in paths if path.startswith(prefix)}


def bundle_stats(paths: set[str], assets: dict[str, dict[str, object]]) -> dict[str, object]:
    rows = [assets[path] for path in paths]
    return {
        "textures": len(paths),
        "png_bytes": sum(int(row.get("output_png_bytes", 0)) for row in rows),
        "estimated_rgba8_bytes": sum(int(row.get("estimated_rgba8_bytes", 0)) for row in rows),
    }


def load_startup_additions(path: Path, asset_paths: set[str]) -> tuple[dict[str, object], set[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError(f"Unsupported preload override schema in {path}")
    startup = data.get("startup_additions")
    if not isinstance(startup, dict):
        raise ValueError(f"Missing startup_additions in {path}")
    paths = startup.get("paths")
    if not isinstance(paths, list) or any(not isinstance(item, str) for item in paths):
        raise ValueError(f"startup_additions.paths must contain strings in {path}")
    if len(paths) != len(set(paths)):
        raise ValueError(f"Duplicate startup addition in {path}")
    invalid = [item for item in paths if not item.startswith("gfx/") or not item.endswith(".png")]
    if invalid:
        raise ValueError(f"Invalid startup addition in {path}: {invalid[0]}")
    missing = sorted(set(paths) - asset_paths)
    if missing:
        raise ValueError(f"Startup addition is absent from the texture namespace: {missing[0]}")
    return startup, set(paths)


def validate_and_render_compiled_tables(manifest: dict[str, object], root: Path) -> str:
    levels = manifest.get("levels")
    global_bundle = manifest.get("global")
    special_bundles = manifest.get("special_bundles")
    assets = manifest.get("assets")
    if not isinstance(levels, dict) or len(levels) != 30:
        raise ValueError(f"Expected exactly 30 level manifests, got {len(levels) if isinstance(levels, dict) else 0}")
    if not isinstance(global_bundle, dict) or not isinstance(special_bundles, dict) or not isinstance(assets, dict):
        raise ValueError("Manifest is missing global, special_bundles, or assets")

    level_definitions = parse_levels(root / "levels/level_defines.h")
    known_enums = {str(level["enum"]): level for level in level_definitions.values()}
    global_paths = global_bundle.get("preload_paths")
    if not isinstance(global_paths, list):
        raise ValueError("global.preload_paths must be a list")

    blocks: dict[str, list[str]] = {"global": global_paths}
    for level_enum, level in levels.items():
        if level_enum not in known_enums:
            raise ValueError(f"Unknown level enum in manifest: {level_enum}")
        if int(level.get("id", -1)) != int(known_enums[level_enum]["id"]):
            raise ValueError(f"Numeric level mismatch for {level_enum}")
        blocks[level_enum] = level.get("preload_paths")
    for name in ("front_end", "ending"):
        bundle = special_bundles.get(name)
        if not isinstance(bundle, dict):
            raise ValueError(f"Missing special bundle: {name}")
        blocks[name] = bundle.get("preload_paths")

    global_set = set(global_paths)
    all_paths: set[str] = set()
    for name, paths in blocks.items():
        if not isinstance(paths, list) or any(not isinstance(path, str) for path in paths):
            raise ValueError(f"{name}.preload_paths must contain strings")
        if len(paths) != len(set(paths)):
            raise ValueError(f"Duplicate path within block {name}")
        for path in paths:
            if not path.startswith("gfx/") or not path.endswith(".png"):
                raise ValueError(f"Invalid preload path in {name}: {path}")
        if name in levels and global_set.intersection(paths):
            raise ValueError(f"Level block {name} repeats paths from the global block")
        all_paths.update(paths)

    skybox_tiles = [path for path in assets if path.startswith("gfx/textures/skybox_tiles/")]
    if len(skybox_tiles) != 627:
        raise ValueError(f"Expected 627 skybox tiles in asset universe, got {len(skybox_tiles)}")
    forbidden = [path for path in all_paths if path.startswith("gfx/textures/skyboxes/")]
    if forbidden:
        raise ValueError(f"Full skybox sources entered preload tables: {forbidden[:3]}")

    sorted_paths = sorted(all_paths)
    if len(sorted_paths) >= 65536:
        raise ValueError(f"uint16_t path index overflow: {len(sorted_paths)} paths")
    path_indices = {path: index for index, path in enumerate(sorted_paths)}

    for path in sorted_paths:
        asset = assets.get(path)
        if not isinstance(asset, dict):
            raise ValueError(f"Missing asset metadata for preload path: {path}")

    def c_ident(name: str) -> str:
        return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")

    def render_indices(symbol: str, paths: list[str]) -> list[str]:
        ordered_paths = sorted(paths)
        indices = [path_indices[path] for path in ordered_paths]
        rows = [f"static const uint16_t {symbol}[] = {{"]
        for offset in range(0, len(indices), 12):
            rows.append("    " + ", ".join(str(index) for index in indices[offset:offset + 12]) + ",")
        rows.append("};")
        return rows

    out = [COMPILED_TABLE_COMMENT, "", "struct GfxPreloadBundle {", "    const uint16_t *indices;", "    uint16_t count;", "    const char *name;", "};", "", "static const char *const gfx_preload_paths[] = {"]
    out.extend(f"    {json.dumps(path)}," for path in sorted_paths)
    out.extend(["};", ""])
    out.extend(render_indices("gfx_preload_global_indices", global_paths))
    out.append("")
    for level_enum in sorted(levels, key=lambda name: int(levels[name]["id"])):
        out.extend(render_indices(f"gfx_preload_{c_ident(level_enum)}_indices", levels[level_enum]["preload_paths"]))
        out.append("")
    for name in ("front_end", "ending"):
        out.extend(render_indices(f"gfx_preload_{name}_indices", blocks[name]))
        out.append("")

    out.extend([
        "#define GFX_PRELOAD_BUNDLE(array_, name_) { array_, (uint16_t) (sizeof(array_) / sizeof((array_)[0])), name_ }",
        "static const struct GfxPreloadBundle gfx_preload_global_bundle =",
        "    GFX_PRELOAD_BUNDLE(gfx_preload_global_indices, \"GLOBAL\");",
        "static const struct GfxPreloadBundle gfx_preload_level_bundles[LEVEL_COUNT] = {",
    ])
    for level_enum in sorted(levels, key=lambda name: int(levels[name]["id"])):
        out.append(f"    [{level_enum}] = GFX_PRELOAD_BUNDLE(gfx_preload_{c_ident(level_enum)}_indices, \"{level_enum}\"),")
    out.extend([
        "};",
        "static const struct GfxPreloadBundle gfx_preload_front_end_bundle =",
        "    GFX_PRELOAD_BUNDLE(gfx_preload_front_end_indices, \"FRONT_END\");",
        "static const struct GfxPreloadBundle gfx_preload_ending_bundle =",
        "    GFX_PRELOAD_BUNDLE(gfx_preload_ending_indices, \"LEVEL_ENDING\");",
        "#undef GFX_PRELOAD_BUNDLE",
        "",
    ])
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--pack-zip", type=Path)
    parser.add_argument("--base-zip", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--unused-output", type=Path)
    parser.add_argument("--manifest-input", type=Path)
    parser.add_argument("--compiled-output", type=Path)
    parser.add_argument(
        "--overrides",
        type=Path,
        default=DEFAULT_OVERRIDES_PATH,
        help="Versioned manual additions, resolved relative to --root",
    )
    args = parser.parse_args()
    root = args.root.resolve()

    if args.manifest_input:
        if not args.compiled_output:
            parser.error("--manifest-input requires --compiled-output")
        manifest = json.loads(args.manifest_input.resolve().read_text(encoding="utf-8"))
        compiled = validate_and_render_compiled_tables(manifest, root)
        args.compiled_output.parent.mkdir(parents=True, exist_ok=True)
        args.compiled_output.write_text(compiled, encoding="utf-8", newline="\n")
        return
    if not args.pack_zip or not args.base_zip or not args.output or not args.unused_output:
        parser.error("generation requires --pack-zip, --base-zip, --output, and --unused-output")

    level_defines = root / "levels/level_defines.h"
    makefile_split = root / "Makefile.split"
    pack_zip_path = args.pack_zip.resolve()
    base_zip_path = args.base_zip.resolve()
    level_definitions = parse_levels(level_defines)
    actor_groups = parse_actor_groups(makefile_split)

    external_pack_entries = load_texture_zip_entries(pack_zip_path)
    base_entries = load_texture_zip_entries(base_zip_path)
    external_pack_paths = {entry["path"] for entry in external_pack_entries}
    base_entry_paths = {entry["path"] for entry in base_entries}
    # Base resources define the complete game texture namespace. External pack
    # entries replace their metadata when present and may add extra overrides.
    entries_by_path = {entry["path"]: entry for entry in base_entries}
    entries_by_path.update({entry["path"]: entry for entry in external_pack_entries})
    pack_entries = list(entries_by_path.values())
    pack_entry_paths = set(entries_by_path)
    for path in REPO_GLOBAL_TEXTURES:
        if path in pack_entry_paths:
            continue
        source = root / path.removeprefix("gfx/")
        if not source.is_file():
            raise ValueError(f"Required repository texture does not exist: {source}")
        width, height = read_png_size(source)
        pack_entries.append({
            "path": path,
            "family": "textures",
            "output_size": [width, height],
            "output_png_bytes": source.stat().st_size,
            "estimated_rgba8_bytes": width * height * 4,
        })

    assets: dict[str, dict[str, object]] = {}
    for entry in pack_entries:
        path = entry["path"]
        rgba_bytes = int(entry["estimated_rgba8_bytes"])
        assets[path] = {
            "path": path,
            "family": entry["family"],
            "output_size": entry["output_size"],
            "output_png_bytes": entry["output_png_bytes"],
            "estimated_rgba8_bytes": rgba_bytes,
            "available_in_base": path in base_entry_paths,
            "available_in_external_pack": path in external_pack_paths,
        }

    asset_paths = set(assets)
    overrides_path = args.overrides if args.overrides.is_absolute() else root / args.overrides
    startup_override, startup_additions = load_startup_additions(overrides_path, asset_paths)

    # levels/scripts.c always loads group0 (Mario and movement effects) and
    # common1 (coins, stars, caps, fire, explosions, doors and global props).
    global_paths: set[str] = set()
    global_categories: dict[str, list[str]] = {}
    for group in ("group0", "common1"):
        group_paths: set[str] = set()
        for actor in actor_groups[group]:
            group_paths |= prefix_matches(asset_paths, f"gfx/actors/{actor}/")
        global_categories[group] = sorted(group_paths)
        global_paths |= group_paths
    segment2 = prefix_matches(asset_paths, "gfx/textures/segment2/")
    global_categories["segment2_hud"] = sorted(segment2)
    global_paths |= segment2
    global_categories["verified_startup_additions"] = sorted(startup_additions)
    global_paths |= startup_additions

    front_end_prefixes = (
        "gfx/levels/intro/", "gfx/levels/menu/", "gfx/textures/title_screen_bg/",
        "gfx/textures/intro_raw/", "gfx/textures/ipl3_raw/",
    )
    front_end_paths = set().union(*(prefix_matches(asset_paths, prefix) for prefix in front_end_prefixes))
    system_prefixes = (
        "gfx/textures/crash_screen/", "gfx/textures/crash_screen_pc/",
        "gfx/textures/touchcontrols/",
    )
    system_paths = set().union(*(prefix_matches(asset_paths, prefix) for prefix in system_prefixes))

    manifests: dict[str, dict[str, object]] = {}
    assigned_gameplay = set(global_paths)
    metadata_mismatches: list[dict[str, object]] = []
    for folder, level in level_definitions.items():
        yaml_path = root / "levels" / folder / "level.yaml"
        script_path = root / "levels" / folder / "script.c"
        if not yaml_path.exists():
            continue
        config = parse_level_yaml(yaml_path)
        script = parse_level_script(script_path)
        texture_bin = script["texture_bin"]
        comparisons = {
            "texture_bin": (config.get("texture-bin"), script["texture_bin"], level["texture_bin_from_level_defines"]),
            "skybox_bin": (config.get("skybox-bin"), script["skybox_bin"], None),
            "effects": (bool(config.get("effects")), script["effects"], None),
            "actor_bins": (sorted(config.get("actor-bins") or []), script["actor_bins"], None),
            "common_bins": (sorted(config.get("common-bin") or []), script["common_bins"], None),
        }
        for field, (yaml_value, script_value, defines_value) in comparisons.items():
            if yaml_value != script_value or (
                field == "texture_bin" and defines_value != script_value
            ):
                metadata_mismatches.append({
                    "folder": folder,
                    "field": field,
                    "level_yaml": yaml_value,
                    "script_c": script_value,
                    "level_defines": defines_value,
                    "selected": script_value,
                })
        categories: dict[str, set[str]] = {
            "level": prefix_matches(asset_paths, f"gfx/levels/{folder}/"),
            "shared_texture_bin": prefix_matches(asset_paths, f"gfx/textures/{texture_bin}/") if texture_bin else set(),
            "skybox": prefix_matches(asset_paths, f"gfx/textures/skybox_tiles/{script['skybox_bin']}.")
                if script["skybox_bin"] else set(),
            "effects": prefix_matches(asset_paths, "gfx/textures/effect/") if script["effects"] else set(),
        }
        for group in list(script["actor_bins"]) + list(script["common_bins"]):
            group_paths: set[str] = set()
            for actor in actor_groups.get(group, []):
                group_paths |= prefix_matches(asset_paths, f"gfx/actors/{actor}/")
            categories[f"actors:{group}"] = group_paths
        specific = set().union(*categories.values()) - global_paths
        effective = specific | global_paths
        assigned_gameplay |= specific
        manifests[level["enum"]] = {
            **level,
            "folder": folder,
            "full_name": config.get("full-name"),
            "config": {
                "texture_bin": texture_bin,
                "skybox_bin": script["skybox_bin"],
                "effects": bool(script["effects"]),
                "actor_bins": script["actor_bins"],
                "common_bins": script["common_bins"],
            },
            "categories": {key: sorted(value - global_paths) for key, value in categories.items()},
            "preload_paths": sorted(specific),
            "stats_world_specific": bundle_stats(specific, assets),
            "stats_cold_with_global": bundle_stats(effective, assets),
        }

    # Ending has no level.yaml, but its own textures and the generic bank are explicit in the build rules.
    ending_paths = (
        prefix_matches(asset_paths, "gfx/levels/ending/")
        | prefix_matches(asset_paths, "gfx/textures/generic/")
        | prefix_matches(asset_paths, "gfx/textures/skybox_tiles/cake.")
    ) - global_paths
    assigned_gameplay |= ending_paths
    special_bundles = {
        "front_end": {
            "preload_paths": sorted(front_end_paths),
            "stats": bundle_stats(front_end_paths, assets),
        },
        "system_conditional": {
            "preload_paths": sorted(system_paths),
            "stats": bundle_stats(system_paths, assets),
        },
        "ending": {
            "preload_paths": sorted(ending_paths),
            "stats": bundle_stats(ending_paths, assets),
        },
    }
    assigned_any = assigned_gameplay | front_end_paths | system_paths | ending_paths
    unassigned = asset_paths - assigned_any
    audit = {
        "texture_assets": len(asset_paths),
        "base_textures": len(base_entry_paths),
        "external_pack_textures": len(external_pack_paths),
        "assigned_to_any_bundle": len(assigned_any),
        "unassigned": len(unassigned),
        "unassigned_paths": sorted(unassigned),
        "interpretation": {
            "assigned": "Covered by conservative source dependencies.",
            "unassigned": "Not covered by gameplay, front-end, ending, or conditional-system rules. Static review is required before removal.",
        },
    }
    output = {
        "schema_version": 3,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "mode": "conservative-per-level",
        "sources": {
            "level_defines": {"path": str(level_defines), "sha256": file_sha256(level_defines)},
            "makefile_split": {"path": str(makefile_split), "sha256": file_sha256(makefile_split)},
            "pack_zip": {"path": str(pack_zip_path), "sha256": file_sha256(pack_zip_path)},
            "base_zip": {"path": str(base_zip_path), "sha256": file_sha256(base_zip_path)},
            "overrides": {"path": str(overrides_path), "sha256": file_sha256(overrides_path)},
        },
        "actor_groups": actor_groups,
        "metadata_mismatches": metadata_mismatches,
        "global": {
            "reason": "group0 + common1 from levels/scripts.c, segment2 HUD, and verified startup additions",
            "categories": global_categories,
            "preload_paths": sorted(global_paths),
            "stats": bundle_stats(global_paths, assets),
        },
        "manual_additions": {
            "startup": {
                "reason": startup_override.get("reason"),
                "evidence": startup_override.get("evidence"),
                "preload_paths": sorted(startup_additions),
                "stats": bundle_stats(startup_additions, assets),
            },
        },
        "levels": manifests,
        "special_bundles": special_bundles,
        "audit": audit,
        "assets": assets,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    args.unused_output.parent.mkdir(parents=True, exist_ok=True)
    args.unused_output.write_text(json.dumps(audit, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if args.compiled_output:
        compiled = validate_and_render_compiled_tables(output, root)
        args.compiled_output.parent.mkdir(parents=True, exist_ok=True)
        args.compiled_output.write_text(compiled, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
